web:
  build: .
  command: python app.py
  ports:
     - "80:5000"
  hostname: hello.weave.local
  environment:
     - "affinity:container!=app_web_*"
redis:
  image: redis
  hostname: redis.weave.local
